version: '3'

networks:
  - ngx-srv-msql-mlcchr:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - ngx-srv-msql-mlcchr

  mysql:
    image: mysql:latest
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'salar' 
      MYSQL_DATABASE: 'salar'
      MYSQL_USER: 'salar'
      MYSQL_PASSWORD: 'salar'
    volumes:
      - ./mysql:/var/lib/mysql

  redis: 
    image: redis:latest
    ports:
      - "6379:6379"

