version: '3'

networks:
  ngx-srv-msql-mlcchr:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./server:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - ngx-srv-msql-mlcchr
    depends_on:
      - server

  server: &server_tem
    image: ${SERVER_IMAGE_NAME}:latest
    container_name: server-container
      #command: php bin/console messenger:consume async -vv
    volumes:
      - ./server:/var/www/project
    depends_on:
      - mysql
      - redis
      - mailer
    networks:
        - ngx-srv-msql-mlcchr

  worker: 
    <<: *server_tem
    container_name: worker-container
    expose: [] 
    command: ["/usr/bin/supervisord"]

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 'salar' 
      MYSQL_DATABASE: 'salar'
      MYSQL_USER: 'salar'
      MYSQL_PASSWORD: 'salar'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
        - ngx-srv-msql-mlcchr

  redis: 
    image: redis:latest
    networks:
        - ngx-srv-msql-mlcchr
  
  
  mailer:
    image: schickling/mailcatcher
    container_name: mailcatcher-container
    ports: 
      - "1025:1025"
      - "1080:1080"
    networks:
        - ngx-srv-msql-mlcchr
